// AUTO-GENERATED by scripts/generate_compliance.ts on 2026-06-02.
//
// Do NOT hand-edit. Re-run `npx tsx scripts/generate_compliance.ts` to
// refresh from official sources. The web app reads this file only; it
// never fetches official pages live.

import type { ResourceKey, StateCode } from "./resourceUrls";

export type ComplianceSummary = {
  state: StateCode;
  topic: ResourceKey;
  // null when the model declined to produce a grounded summary from
  // the fetched source pages. ComplianceCard renders these entries
  // as the "Summary coming soon" coming-soon variant.
  title: string | null;
  summary: string | null;
  sources: string[];
  last_checked: string;
};

export const COMPLIANCE_SUMMARIES: ComplianceSummary[] = [
  {
    "state": "ID",
    "topic": "at_will",
    "title": "Idaho At-Will Employment Termination Rules and Key Exceptions",
    "summary": "Idaho is an at-will employment state, meaning either the employer or employee may end the employment relationship at any time, with or without notice and with or without cause. However, employers may not terminate an employee for a discriminatory or retaliatory reason, or in violation of public policy. If an employer policy, employment contract, or union agreement exists, the employment relationship may be subject to those terms. Employers with discrimination questions may contact the Idaho Human Rights Commission.",
    "sources": [
      "https://www.labor.idaho.gov/businesses/labor-laws/labor-laws-faq/"
    ],
    "last_checked": "2026-06-02"
  },
  {
    "state": "ID",
    "topic": "business_tax",
    "title": "Idaho Business Income Tax for Insurance Agencies",
    "summary": "Idaho taxes businesses on net income (profit), not gross receipts. For 2025, the Idaho business income tax rate on taxable income is 5.3%. Insurance agencies organized as pass-through entities — such as partnerships, LLCs, or S corporations — generally have income flow through to owners' personal returns rather than paying tax at the entity level, though the state's affected business entity election allows partnerships and S corporations to optionally pay Idaho income tax at the entity level. Agencies should confirm their specific situation with a tax professional.",
    "sources": [
      "https://tax.idaho.gov/taxes/income-tax/business-income/online-guide/",
      "https://tax.idaho.gov/taxes/income-tax/business-income/guides-for-certain-businesses/pass-through-entities/"
    ],
    "last_checked": "2026-06-02"
  },
  {
    "state": "ID",
    "topic": "leave",
    "title": "Idaho Leave Laws: No State Program, Federal FMLA Applies",
    "summary": "Idaho has no state-specific paid family or medical leave program and no state paid sick leave mandate. Federal FMLA, administered by the U.S. Department of Labor, may apply to larger Idaho employers: private-sector employers with 50 or more employees in 20 or more workweeks are covered. Eligible employees may take up to 12 workweeks of unpaid, job-protected leave per year for qualifying family and medical reasons, or up to 26 workweeks for military caregiver leave.",
    "sources": [
      "https://www.labor.idaho.gov/businesses/labor-laws/labor-laws-faq/",
      "https://www.dol.gov/agencies/whd/fmla"
    ],
    "last_checked": "2026-06-02"
  },
  {
    "state": "ID",
    "topic": "salary_threshold",
    "title": "Idaho Salary & Exempt Thresholds Follow Federal FLSA Standard",
    "summary": "Idaho does not set its own overtime-exempt salary threshold for white-collar exemptions. The state follows the federal Fair Labor Standards Act standard administered by the U.S. Department of Labor's Wage and Hour Division. The federal level has changed and been subject to legal challenge, so employers should confirm the current figure directly with the U.S. Department of Labor before making classification decisions.",
    "sources": [
      "https://www.dol.gov/agencies/whd/overtime",
      "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-V/subchapter-A/part-541/subpart-G/section-541.600"
    ],
    "last_checked": "2026-06-02"
  },
  {
    "state": "ID",
    "topic": "wage_hour",
    "title": "Idaho Wage & Hour Labor Law Key Requirements FAQ",
    "summary": "Idaho's current minimum wage is $7.25 per hour, with $3.35 per hour for tipped employees and $4.25 per hour for new hires under 20 for their first 90 consecutive calendar days. Overtime must be paid at time and one-half for all hours worked over 40 in a workweek under the federal Fair Labor Standards Act. Final paychecks after separation are due by the next scheduled payday or within 10 days, and employers may not withhold wages without written authorization or legal requirement.",
    "sources": [
      "https://www.labor.idaho.gov/businesses/labor-laws/labor-laws-faq/"
    ],
    "last_checked": "2026-06-02"
  },
  {
    "state": "UT",
    "topic": "business_tax",
    "title": "Utah Business Income Tax Rules for Insurance Agencies by Entity Type",
    "summary": "Utah taxes business net income, not gross receipts, so which tax applies depends entirely on the agency's entity structure. C corporations file a corporate franchise tax return (Form TC-20) and owe a minimum privilege tax of $100; the current individual income tax flat rate of 4.5% applies to owners of pass-through entities and sole proprietorships whose business income flows to their personal returns. Agencies should confirm their entity structure with a qualified tax professional to determine which obligation applies.",
    "sources": [
      "https://tax.utah.gov/business/corporate-income-tax/c-corp-tax/",
      "https://incometax.utah.gov/paying/tax-rates"
    ],
    "last_checked": "2026-06-02"
  },
  {
    "state": "UT",
    "topic": "leave",
    "title": "Utah Leave Laws: No State Program, Federal FMLA Applies",
    "summary": "Utah has no state-specific paid family or medical leave program and no state paid sick leave mandate. Eligible employees of covered employers may still have rights under the federal Family and Medical Leave Act (FMLA), administered by the U.S. Department of Labor. The FMLA covers private-sector employers with 50 or more employees in 20 or more workweeks, and provides eligible employees up to 12 workweeks of unpaid, job-protected leave per year for qualifying family and medical reasons, or up to 26 workweeks for military caregiver leave.",
    "sources": [
      "https://laborcommission.utah.gov/divisions/utah-antidiscrimination-and-labor-uald/",
      "https://www.dol.gov/agencies/whd/fmla"
    ],
    "last_checked": "2026-06-02"
  },
  {
    "state": "UT",
    "topic": "salary_threshold",
    "title": "Utah Salary & Exempt Thresholds Follow Federal FLSA Standard",
    "summary": "Utah does not set its own salary threshold for white-collar overtime exemptions; employers must follow the federal Fair Labor Standards Act standard. The FLSA requires that exempt executive, administrative, and professional employees meet federal salary level requirements. The federal threshold has changed and been subject to legal challenge, so the current figure should be confirmed directly with the U.S. Department of Labor.",
    "sources": [
      "https://www.dol.gov/agencies/whd/overtime",
      "https://www.ecfr.gov/current/title-29/subtitle-B/chapter-V/subchapter-A/part-541/subpart-G/section-541.600"
    ],
    "last_checked": "2026-06-02"
  },
  {
    "state": "UT",
    "topic": "wage_hour",
    "title": "Utah Minimum Wage and Overtime Pay Requirements",
    "summary": "Utah's minimum wage is $7.25 per hour. Employers may pay a training wage of $4.25 per hour for the first 90 days of employment for minors, and tipped employees may be paid $2.13 per hour provided their tips bring total compensation to at least minimum wage. Utah has no separate state overtime law; overtime is governed by the federal FLSA, which requires pay at one-and-one-half times the regular rate for hours worked over 40 in a workweek.",
    "sources": [
      "https://laborcommission.utah.gov/divisions/utah-antidiscrimination-and-labor-uald/wage-claim/",
      "https://www.dol.gov/agencies/whd/fact-sheets/23-flsa-overtime-pay"
    ],
    "last_checked": "2026-06-02"
  },
  {
    "state": "WA",
    "topic": "at_will",
    "title": "Washington At-Will Termination Rules and Retaliation Protections",
    "summary": "Washington is an at-will employment state, meaning employers may end employment at any time, for any reason or no reason, without cause or advance notice. However, employers cannot terminate or retaliate against employees for exercising protected rights, filing complaints, or for reasons involving discrimination, protected leave, safety complaints, or immigration-related threats. Employees who believe they have been unlawfully terminated or retaliated against may file a complaint with Washington Labor & Industries.",
    "sources": [
      "https://www.lni.wa.gov/workers-rights/workplace-policies/termination-retaliation"
    ],
    "last_checked": "2026-06-01"
  },
  {
    "state": "WA",
    "topic": "business_tax",
    "title": "Washington B&O Tax Rate for Insurance Agent and Broker Commissions",
    "summary": "Washington's Business & Occupation (B&O) tax is a gross-receipts tax with no deductions for labor, materials, or other business costs. Insurance agent and broker commission income falls under its own B&O classification taxed at 0.484%. Rates are classification-specific, so an agency with other revenue streams may fall under additional classifications at different rates. Agencies should confirm all applicable classifications with the Washington Department of Revenue.",
    "sources": [
      "https://dor.wa.gov/taxes-rates/business-occupation-tax",
      "https://dor.wa.gov/taxes-rates/business-occupation-tax/business-occupation-tax-classifications",
      "https://dor.wa.gov/open-business"
    ],
    "last_checked": "2026-06-01"
  },
  {
    "state": "WA",
    "topic": "hiring",
    "title": "Washington Workers' Rights Overview from L&I",
    "summary": "Washington workers are protected by laws covering wages, working conditions, overtime pay, and prevailing wage on public works projects. The state's Department of Labor & Industries handles workplace discrimination related to safety, health, wage and hour, and other areas. Washington does not require employers to provide leave or pay for holidays, vacations, or bereavement.",
    "sources": [
      "https://www.lni.wa.gov/workers-rights/"
    ],
    "last_checked": "2026-05-28"
  },
  {
    "state": "WA",
    "topic": "leave",
    "title": "Washington State Paid Sick Leave and Paid Family & Medical Leave",
    "summary": "Washington employers must provide paid sick leave, accruing at one hour for every 40 hours worked, with unused balances of 40 hours or less carrying over each year. Employees may use leave for illness, family care, domestic violence reasons, and — as of July 27, 2025 — immigration proceedings. Washington also offers Paid Family and Medical Leave, a separate benefit providing paid time off for serious health conditions, family care, bonding with a new child, or military family needs. The source pages do not state the current Paid Family and Medical Leave premium rate or employer/employee contribution split.",
    "sources": [
      "https://www.lni.wa.gov/workers-rights/leave/paid-sick-leave/",
      "https://paidleave.wa.gov/"
    ],
    "last_checked": "2026-06-01"
  },
  {
    "state": "WA",
    "topic": "nexus",
    "title": "Washington Insurance Producer and Adjuster Licensing Overview",
    "summary": "Washington state requires insurance producers, adjusters, and business entities to obtain a license before selling or adjusting insurance. Licenses can be obtained, renewed, or managed through the National Insurance Producer Registry's Licensing Center or the state's online portal. Producers must also meet continuing education and compliance requirements to maintain their license.",
    "sources": [
      "https://www.insurance.wa.gov/producers-adjusters/licensing",
      "https://dor.wa.gov/open-business"
    ],
    "last_checked": "2026-05-28"
  },
  {
    "state": "WA",
    "topic": "payroll",
    "title": "Washington Employer Unemployment Tax Payment Requirements",
    "summary": "Washington employers with employees in the state are generally required to pay unemployment taxes on gross wages up to a taxable wage base. Employers must first obtain a business license through the Department of Revenue, then file quarterly tax and wage reports and make payments online or by mail. Employers unable to pay in full may request a deferred payment plan to avoid higher delinquent tax rates and certain collection actions.",
    "sources": [
      "https://esd.wa.gov/employer-requirements/unemployment-taxes/employers-guide-paying-taxes",
      "https://dor.wa.gov/open-business"
    ],
    "last_checked": "2026-05-28"
  },
  {
    "state": "WA",
    "topic": "remote",
    "title": null,
    "summary": null,
    "sources": [
      "https://www.lni.wa.gov/workers-rights/"
    ],
    "last_checked": "2026-05-28"
  },
  {
    "state": "WA",
    "topic": "salary_threshold",
    "title": "Washington Overtime-Exempt Salary Thresholds for 2026",
    "summary": "Starting January 1, 2026, both small employers (1–50 employees) and large employers (51 or more employees) must pay overtime-exempt salaried workers at least 2.25 times the state minimum wage — calculated as 2.25 × $17.13 × 40 = $1,541.70 per week. The two employer tiers currently match at this threshold. The state minimum wage for 2025 is $16.66 per hour, rising to $17.13 in 2026; thresholds update every January 1. Washington's thresholds exceed the federal threshold, so employers must meet the higher state figure.",
    "sources": [
      "https://www.lni.wa.gov/workers-rights/wages/overtime/changes-to-overtime-rules"
    ],
    "last_checked": "2026-06-01"
  },
  {
    "state": "WA",
    "topic": "termination",
    "title": "Washington WARN Act Requirements for Mass Layoffs and Closures",
    "summary": "Washington's Mass Layoffs and Business Closings law requires employers to provide written notice 60 days before qualifying layoffs, facility closures, or significant hour reductions. Employers must notify the state, affected employees, and the local community's chief elected official. Employers who fail to comply may face daily financial penalties, though penalties can be reduced by providing back pay and benefit value to affected employees.",
    "sources": [
      "https://www.lni.wa.gov/workers-rights/wages/getting-paid/",
      "https://esd.wa.gov/employer-requirements/layoffs-and-employee-notifications/warn-requirements"
    ],
    "last_checked": "2026-05-28"
  },
  {
    "state": "WA",
    "topic": "wa_cares",
    "title": "Washington WA Cares Fund Employer Premium Collection Requirements",
    "summary": "Washington employers must collect WA Cares Fund premiums from employees each quarter and report wages and hours alongside Paid Leave reporting. The premium is 0.58% of an employee's gross wages, and unlike Paid Leave, contributions are not capped at the social security taxable maximum. Employers pay no share of the premium but may elect to cover some or all of an employee's share. Employers must keep exemption approval letters on file and must not deduct premiums from exempt workers.",
    "sources": [
      "https://wacaresfund.wa.gov/",
      "https://wacaresfund.wa.gov/employers/"
    ],
    "last_checked": "2026-06-01"
  },
  {
    "state": "WA",
    "topic": "wage_hour",
    "title": "Washington State Minimum Wage and Overtime Pay Requirements",
    "summary": "Washington employers must pay most employees at least $17.13 per hour in 2026, up from $16.66 per hour in 2025. Overtime pay must be at least 1.5 times the employee's regular hourly rate for all hours worked over 40 in a 7-day workweek. Employers must pay overtime regardless of their size, and employees cannot waive their right to overtime. Some salaried workers meeting executive, administrative, or professional definitions are exempt from overtime requirements.",
    "sources": [
      "https://www.lni.wa.gov/workers-rights/wages/minimum-wage/",
      "https://www.lni.wa.gov/workers-rights/wages/overtime/"
    ],
    "last_checked": "2026-06-01"
  },
  {
    "state": "WA",
    "topic": "workers_comp",
    "title": "Washington Workers' Compensation Insurance Overview and Premium Rates",
    "summary": "Washington's workers' compensation program provides no-fault industrial insurance coverage for most employers and workers in the state. Quarterly reports and premiums are due four times per year. The average premium rate is set to rise in 2026, and employers can look up risk classes, self-insured employers, and account information through the state's online portal.",
    "sources": [
      "https://www.lni.wa.gov/insurance/"
    ],
    "last_checked": "2026-05-28"
  }
];
