// AUTO-GENERATED by scripts/generate_compliance.ts.
//
// Do NOT hand-edit this file beyond updating the seed values below — re-run
// `npx tsx scripts/generate_compliance.ts` to refresh from official sources.
// The web app reads this file only; it never fetches official pages live.
//
// ⚠️  PLACEHOLDER STATUS — pending first real regeneration. ⚠️
// These WA entries are HAND-SEEDED from ui-reference.html samples so the
// page has something to render. They have NOT been produced by the
// generation pipeline. The first task of step 12 (pinned in spec.md
// "Build order") is to run the real generator and verify grounding
// against hand-validated reference summaries for WA Wage & Hour and Leave.
// Until that runs and is verified, treat these summaries as illustrative
// placeholders, not grounded outputs.
//
// Seed coverage:
//   - WA: 7 of 8 topics. Remote Work intentionally omitted so the
//     coming-soon fallback path renders for that cell.
//   - AZ / CO / ID / MT / NV / OR / UT: no stored summaries; every cell
//     renders the "Summary coming soon" fallback (which still shows the
//     topic tag, state badge, and any mapped source links).

import type { ResourceKey, StateCode } from "./resourceUrls";

export type ComplianceSummary = {
  state: StateCode;
  topic: ResourceKey;
  title: string;
  summary: string;
  sources: string[];     // exact URLs the summary was generated from
  last_checked: string;  // ISO date the regeneration job ran
};

// Date marker for the seed. Real regenerations stamp the run date.
const SEED_DATE = "2026-05-28";

export const COMPLIANCE_SUMMARIES: ComplianceSummary[] = [
  {
    state: "WA",
    topic: "wage_hour",
    title: "Washington Minimum Wage & Overtime",
    summary:
      "Washington's minimum wage rises each year with inflation and applies to most employees regardless of employer size. Workers generally earn 1.5× their regular pay for hours worked over 40 in a week. Tips belong to employees and cannot be counted toward the minimum-wage obligation.",
    sources: [
      "https://www.lni.wa.gov/workers-rights/wages/minimum-wage/",
      "https://www.lni.wa.gov/workers-rights/wages/overtime/",
    ],
    last_checked: SEED_DATE,
  },
  {
    state: "WA",
    topic: "leave",
    title: "Washington Paid Sick Leave & PFML",
    summary:
      "Employees accrue at least 1 hour of paid sick leave for every 40 hours worked, available for personal or family health needs. The state Paid Family & Medical Leave program offers paid time off for qualifying medical and family events, funded by premiums shared between employer and employee.",
    sources: [
      "https://www.lni.wa.gov/workers-rights/leave/paid-sick-leave/",
      "https://paidleave.wa.gov/",
    ],
    last_checked: SEED_DATE,
  },
  {
    state: "WA",
    topic: "payroll",
    title: "Washington Employer Payroll Taxes",
    summary:
      "Employers report and pay unemployment, Paid Leave, and WA Cares contributions to the Employment Security Department on a quarterly basis. New employers must first obtain a business license through the Department of Revenue before they can register and file.",
    sources: [
      "https://esd.wa.gov/employer-requirements/unemployment-taxes/employers-guide-paying-taxes",
      "https://dor.wa.gov/open-business/business-licensing",
    ],
    last_checked: SEED_DATE,
  },
  {
    state: "WA",
    topic: "workers_comp",
    title: "Washington Workers' Compensation",
    summary:
      "Washington runs a monopolistic state-fund workers' compensation system administered by Labor & Industries — coverage must be purchased through L&I rather than a private insurer. Nearly all employers must carry coverage and report worker hours on a quarterly basis.",
    sources: [
      "https://www.lni.wa.gov/insurance/",
    ],
    last_checked: SEED_DATE,
  },
  {
    state: "WA",
    topic: "termination",
    title: "Washington Final Pay & Layoff Notice",
    summary:
      "Final wages must be paid by the employee's next regular payday whether they quit or were discharged. Employers with significant headcount must provide advance notice before covered mass layoffs or business closures under state and federal WARN rules.",
    sources: [
      "https://www.lni.wa.gov/workers-rights/wages/getting-paid/",
      "https://esd.wa.gov/employer-requirements/layoffs-and-employee-notifications/warn-requirements",
    ],
    last_checked: SEED_DATE,
  },
  {
    state: "WA",
    topic: "nexus",
    title: "Washington Producer Licensing",
    summary:
      "Insurance producers must be licensed through the Washington Office of the Insurance Commissioner, with specific lines of authority for the products they sell. Businesses must also register with the Department of Revenue, which establishes tax nexus.",
    sources: [
      "https://www.insurance.wa.gov/producers-adjusters/licensing",
      "https://dor.wa.gov/open-business/business-licensing",
    ],
    last_checked: SEED_DATE,
  },
  {
    state: "WA",
    topic: "hiring",
    title: "Washington Hiring Requirements",
    summary:
      "Employers in Washington must meet wage, paid-sick-leave, and workplace-standards obligations from an employee's first day. L&I's employment-standards resources cover the core obligations new employers need to satisfy when bringing on staff.",
    sources: [
      "https://www.lni.wa.gov/workers-rights/",
    ],
    last_checked: SEED_DATE,
  },
  // Remote Work intentionally omitted from the seed — Washington has no
  // single dedicated remote-work statute, and the mapped URL is a general
  // employment-standards hub rather than a topic-specific page. Leaving it
  // unseeded lets the page render the "Summary coming soon" fallback with
  // the official source link still visible.
];
