// All 50 US states. `data_coverage: true` is the ONLY flag that makes a
// state selectable in the Licensed-states grid; expanding coverage = flip
// the flag (no other code changes). `validated` reflects AM Best cross-check
// and is only meaningful where data_coverage is true.

export type StateRecord = {
  readonly code: string;
  readonly name: string;
  readonly data_coverage: boolean;
  readonly validated?: { readonly auto: boolean; readonly home: boolean };
  // Provenance of a covered state's data. Absent/"scraped" = SERFF scrape;
  // "ambest" = interim AM Best industry data (not yet directly scraped).
  readonly source?: "scraped" | "ambest";
};

export const STATES: readonly StateRecord[] = [
  { code: "AL", name: "Alabama",        data_coverage: false },
  { code: "AK", name: "Alaska",         data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-05 (interim->real): 100-row SERFF scrape, 189/189 in-target. Coverage-thin AM Best (53 in-target): value-agreement on SHARED filings 41/41 (100%), interim 41/41 (0 disagreements), PPA in-window 34/34 (100%) / HO 13/13 (100%). Scrape RICHER (59 scrape-only) — genuine Country enrichment (12 rate rows vs AM Best's 2) + 0% filings, sub-types, back-extension. (Farmers/Liberty file only Form/Rule in AK, no rates → AM Best correctly 0, NOT a gap.) 0 material soft-miss (6 AM-Best-only all recency/immaterial). Recovered 2 material COUNTRY CFPC (wrapped-name bug) incl. CFPC-134283900 +9.6%/9,644ph Prospect signal -> both validated.
  { code: "AZ", name: "Arizona",        data_coverage: true,  validated: { auto: true,  home: true  } },
  { code: "AR", name: "Arkansas",       data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-11 (interim->real): 186-row SERFF scrape, 333/333 cached, 0 misses (24-state streak). Cross-check (22nd point): headline deflation traced ENTIRELY to two AM-BEST-SIDE entity transpositions (6th/7th corrected at source — PRGS 5-entity + FARM flex-home 3-entity blocks; ours match the CRI tables field-for-field); 0 genuine soft-misses -> both validated
  { code: "CA", name: "California",     data_coverage: true,  source: "ambest" }, // PERMANENT (non-SERFF) — see AMBEST_PERMANENT_STATES
  { code: "CO", name: "Colorado",       data_coverage: true,  validated: { auto: false, home: false } },
  { code: "CT", name: "Connecticut",    data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-09 (interim->real): 137-row SERFF scrape, 359/359 in-target cached, 0 download misses (15-state streak). THE STATE THAT SURFACED B14 (4th filing-type-vocabulary variant): CT is a flex-rating state and its "Flex Rate" SERFF filing type failed the Rate/Rate-Rule gate — live PPA signals silently dropped (GEICO Choice +6.0%/12,316ph + GEICO Secure +5.8%/89,618ph eff 01/22/26; Progressive Direct +6.0%/182,485ph eff 02/27/26), caught pre-ship by the cross-check, fixed exact-match, retro-swept all 25 prior states A/B: 0 Flex Rate exposure anywhere (B14_SWEEP.md). Post-fix cross-check (15th interim->real point): value-agreement 55/56 (98.2%; the 1 differ = AM Best zeroing a REJECTED Allstate NA filing, ours source-true), PPA 43/54 / HO 25/33 (all AM-Best-only = recency/0%-immaterial/1 adjudicated new-product), 0 genuine soft-misses; Farmers enrichment: 2 material filings AM Best lacks -> both validated
  { code: "DE", name: "Delaware",       data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-08 (interim->real): 133-row SERFF scrape, 237/237 in-target cached, 0 download misses (14-state streak). THE STATE THAT SURFACED THE 3rd SILENT-DROP CLASS: a None-vs-False three-valued-logic bug in the shared rate_data_applies gate (variant-layout PDFs omit the rate-data sentence) silently dropped 4 MATERIAL clusters here (SF -1.5%/244,139ph ACTIVE; Encompass +8.6%; Allstate +17.5%; the Nationwide 24,671ph trio) — caught pre-ship by the cross-check, fixed globally, full-B6-protocol scan recovered 10 more rows across 5 shipped states (all non-live). Post-fix cross-check (14th interim->real point): value-agreement 64/64 (100%), interim 57/57 (0 disagreements), PPA 58/59 (98.3%), HO 19/25 (all 6 AM-Best-only = 2026 recency) -> adjudicated in-window 100%/100%. GEICO-dominated market; coverage RICHNESS-ONLY -> both validated
  { code: "FL", name: "Florida",        data_coverage: false },
  { code: "GA", name: "Georgia",        data_coverage: true,  validated: { auto: true,  home: true  } },
  { code: "HI", name: "Hawaii",         data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-01 (interim->real): 71-row SERFF scrape, 138/138 in-target. AM Best cross-check CLEANEST YET: PPA 44/44 (100%) / HO 7/7 (100%) corroboration, interim 41/41 (100%) impact agreement — 0 disagreements, 0 soft-misses, 0 recoveries, 0 parser flags. AmFam pre-resolved = 0 genuine. HO small-N (7) read in-context: robust PPA leg 44/44 -> both validated.
  { code: "ID", name: "Idaho",          data_coverage: true,  validated: { auto: true,  home: false } },
  { code: "IL", name: "Illinois",       data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-06-25 (interim->real): 303-row SERFF scrape, 600/602 filings. AM Best cross-check: PPA 93.8% / HO 95.2% corroboration, 155/156 interim-impact agreement. 1 immaterial coverage gap (Liberty HO, AM Best-covered) -> both validated.
  { code: "IN", name: "Indiana",        data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-16 (interim->real): 244-row SERFF scrape, 438/438 cached, 0 download misses (29-state streak). Cross-check: value-agreement 130/130 (100%), PPA 101/108 (93.5%) / HO 55/56 (98.2%), 0 impact disagreements. 0 material soft-misses (8 AM-Best-only rows ALL 0.0% impact: 1 immaterial Allstate NA 0ph + 7 recency — GEICO's 6/15/26 six-entity batch and Allstate NA 5/12/26, past the 4/17/26 scrape window). RICHNESS-ONLY on all four thin-brand funnels (Country/GEICO/Farmers/Encompass) — AM Best complete on material rate filings. Import brand gate caught Consolidated Insurance Company (4 HO rows) — legacy Peerless/Indiana-group LM vehicle riding LBPM filings with Peerless Indemnity + LM Ins Corp (excluded on the same filing) -> Peerless doctrine, added to EXCLUDED_SUBSIDIARY_PATTERNS -> both validated
  { code: "IA", name: "Iowa",           data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-10 (interim->real): 195-row SERFF scrape, 429/429 cached (biggest state: 1,184 universe), 0 misses (19-state streak). Cross-check (17th point): PPA 92.9% / HO 91.9%, value-agreement 107/108 (99.1%; the 1 differ = AM Best carrying an impossible -158.0% — ours -15.000% == source PDF, 5th AM-Best-side error corrected at source). Blank max/min x20 = the SD source-blank family, all impacts populated -> both validated
  { code: "KS", name: "Kansas",         data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-09 (interim->real): 170-row SERFF scrape, 311/311 cached, 0 misses (16-state streak). Cross-check (16th point): value-agreement 68/68 (100%, 2nd perfect); COUNTRY richness-only (AK-thinness does NOT reproduce in plains, 14th confirmation); Encompass enrichment x2 AM Best lacks; Metropolitan P&C excluded (legacy-MetLife family) -> both validated
  { code: "KY", name: "Kentucky",       data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-12 (interim->real): 216-row SERFF scrape, 422/422 cached, 0 misses (25-state streak). Cross-check (23rd point): value-agreement 134/135 (99.3%), 0 material flags -> both validated
  { code: "LA", name: "Louisiana",      data_coverage: false },
  { code: "ME", name: "Maine",          data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-08 (interim->real): 114-row SERFF scrape, 309/309 in-target cached, 0 true misses (12-state streak). AM Best cross-check (12th interim->real point, CLEANEST YET): value-agreement 48/48 (100% — first perfect) / interim 46/46 (0 disagreements); adjudicated in-window PPA 45/45 + HO 18/18 (headline 82.7/94.7 deflated only by 2026-eff recency + one LBPM pair AM Best carried at a pre-final stage — source PDF shows both entities 0.000%, ours source-true). THE ISOLATION-BOUNDARY TEST: ME (small/rural/somewhat-isolated) resolves ND/RI-COMPLETE — Nationwide 25-vs-6 and Travelers 23-vs-4 watch-points both adjudicated Form/Rule-richness (the 1 material Travelers Quantum +7.5%/16,008ph IS in AM Best); thinness stays AK-Country-specific -> both validated (HO N=19 mid-N read with the perfect PPA leg, the ND precedent)
  { code: "MD", name: "Maryland",       data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-11 (interim->real): 206-row SERFF scrape, 546/546 cached (biggest state: 1,441 universe), 0 misses (22-state streak). Cross-check (20th point): PPA 92.8% / HO 97.2%, value-agreement 69/69 (100%, 5th perfect), 0 material flags -> both validated
  { code: "MA", name: "Massachusetts",  data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-06 (interim->real): 129-row SERFF scrape (LM P&C + Wausau family excluded per the LM-vehicle doctrine), 281/282 in-target (the 1 a Rule filing). AM Best cross-check: PPA 37/38 (97.4%, the 1 miss pure recency) / HO 27/27 (100% — FIRST robust-N home read), value-agreement on shared 53/53 (100%), interim 49/49 (0 disagreements, 9th interim->real point). Coverage verdict: richness-only (GEICO/Progressive/Farmers form/rule-heavy per-brand — the AK resolution) + 1 GEICO enrichment (GECC-134365103 +3.7% AM Best lacks). NICOA paginator-glitch save corroborated -> both validated
  { code: "MI", name: "Michigan",       data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-15 (interim->real): 280-row SERFF scrape, 542/542 cached, 0 download misses (28-state streak). Cross-check: value-agreement 103/103 (100%, 7th perfect), PPA 78/91 (85.7%) / HO 49/53 (92.5%). B18 recovery pre-import: PRGS-134425693/-680 ("new product rating model" FP) — Progressive Marathon -2.0%/556,624 + Progressive Michigan -4.4%/259,667 Defend-class on the full MI book. THE STATE THAT SURFACED B19 (5th silent-drop class): stale EFFECTIVE_DATE_TO=04/17/2026 was dropping in-force filings (USAA +7.0%/22,492; PRGS -2.8/-2.7 on 585k/238k) — window bumped to 12/31/2026, 39-state retro sweep recovered 552 rows / 360 filings map-wide. Farmers Mutual of MI (AAIS independent) tripwired -> both validated
  { code: "MN", name: "Minnesota",      data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-22 (interim->real): 281-row SERFF scrape, 532/532 targets cached. Cross-check: value-agreement 126/126 (100%), PPA 76/80 (95.0%) / HO 58/61 (95.1%). MATERIAL soft-miss RECOVERED pre-import: Illinois Farmers PPA +2.7%/34,169ph (FARM-134852026) — FIG midwest vehicle invisible to the prefix-anchored "farmers" search when filing SOLO (its co-filed rows always rode FIE filings); recovered via targeted search, values exact-match AM Best, term added to config SEARCH + GROUP_SEARCH (the WV-Liberty fix family). 1 impact disagreement resolved OURS-CORRECT (ALSE-134650317: PDF explicitly 0.000%, AM Best 24.9% is their error). 1 SERFF-visibility watch item (Allstate NA HO -2.7%/8,798: filing ALSE-134637798 is "Rate data does NOT apply" + state resubmission note — values never in public summary; MS-precedent class). Funnels: 3x RICHNESS-ONLY + Farmers GENUINE UNDERCOUNT in OUR favor (FARM-134642886 +6.655%/94,374ph absent from AM Best) -> both validated
  { code: "MS", name: "Mississippi",    data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-10 (interim->real): 159-row SERFF scrape, 317/317 cached, 0 misses (18-state streak). Cross-check: value-agreement 84/84 (100%, 3rd perfect); 8 AM-Best-only rows = 2 SERFF-invisible clusters (USAA 04/16/26, Nationwide 04/06/26 — documented visibility-gap watch items); mga insurance genuine SERFF presence (first since GA) -> both validated
  { code: "MO", name: "Missouri",       data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-21 (interim->real): 330-row SERFF scrape, 538/538 targets cached. Cross-check: value-agreement 149/149 (100%), PPA 89/93 (95.7%) / HO 65/66 (98.5%); 5 impact disagreements are the known interim->real class (PRGS-134594980 four subsidiaries + CFPC-134282220 — AM Best interim values, our final-PDF values win). 1 flagged material soft-miss ADJUDICATED as AM Best double-list artifact: the TIE "PPA 12/12/25" row duplicates the TIE HO 06/08/26 row on all four values (ind 8.9/imp 2.5/ph 5,699/wp 1,340,242) and Truck Insurance Exchange has zero personal-auto presence among its 42 MO SERFF filings. Remaining AM-Best-only: 3 recency past the 4/17/26 scrape window (incl Liberty Mutual Personal 2.0%/13,766ph — refresh watch item) + 1 immaterial Allstate NA 0%/0ph. Zero-row audit: 6 filings all zero-value — 3 Encompass complete-market-exit notices (MO HO AND PPA, Remedial Action B.2, eff 03/26/26), 2 Travelers withdrawals/blank adoption, 1 Allstate RV withdrawal. RICHNESS-ONLY on all four thin-brand funnels (Country/GEICO/Farmers/Encompass); import brand gate 0 unmatched -> both validated
  { code: "MT", name: "Montana",        data_coverage: true,  validated: { auto: true,  home: true  } },
  { code: "NE", name: "Nebraska",       data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-10 (interim->real): 193-row SERFF scrape, 327/327 cached, 0 misses (21-state streak). THE CLEANEST CROSS-CHECK YET (19th point): PPA 97.1% / HO 96.3%, value-agreement 83/83 (100%, 4th perfect), 0 material flags — first nothing-to-adjudicate state. B9 tripwire home state (Farmers Mutual of Nebraska): 0 independents leaked -> both validated
  { code: "NV", name: "Nevada",         data_coverage: true,  validated: { auto: true,  home: false } },
  { code: "NH", name: "New Hampshire",  data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-06-29 (interim->real): 113-row SERFF scrape, 214/214 in-target. AM Best cross-check (in-window): PPA 22/22 (100%) / HO 14/14 (100%) corroboration, interim 33/33 (100%) impact agreement — cleanest yet (0 disagreements). Recovered the Safeco General Insurance Co of America soft-miss (eff 01/19/25 +15.8%/3711ph) via the 2nd search-term fix -> both validated.
  { code: "NJ", name: "New Jersey",     data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-10 (interim->real): 182-row SERFF scrape, 258/258 cached, 0 misses (17-state streak). THE STATE THAT SURFACED B16 (5th/6th filing-type vocabularies: Prior/Expedited/Limited Prior Approval + Form/Rate(/Rule)) — live GEICO +13.0%/198,263ph + Allstate book recovered pre-ship; 25-prior-state audit -> 12-state gated correction. Post-fix cross-check: value-agreement 65/66 (98.5%), HO 95%; ALSE-133980775 exhibit-junk cleaned (B17 opened); Drive New Jersey -> Progressive (live NJ writer) -> both validated
  { code: "NM", name: "New Mexico",     data_coverage: true,  validated: { auto: true,  home: true  } },
  { code: "NY", name: "New York",       data_coverage: true,  source: "ambest" }, // PERMANENT (DFS, non-SERFF) — see AMBEST_PERMANENT_STATES
  { code: "NC", name: "North Carolina", data_coverage: false }, // EXCLUDED: structural NCRB Rate-Bureau gap (no per-carrier AM Best data); not fixable via this source
  { code: "ND", name: "North Dakota",   data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-07 (interim->real): 114-row SERFF scrape (121->114 after the B9 bare-"farmers" fix dropped 7 independent-mutual rows), 290/290 in-target cached, 0 true misses (10-state streak). AM Best cross-check (10th interim->real point): value-agreement on shared 44/44 (100%), interim 45/45 (0 disagreements), in-window PPA 35/35 + HO 20/20 (100%). Coverage verdict: richness-only on all 4 divergence brands. B9 surfaced HERE: bare-"farmers" had mislabeled 13 independent mutuals (~86 interim rows / 12 states) as Farmers — fixed globally in the same import -> both validated
  { code: "OH", name: "Ohio",           data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-06-24 (interim->real); AM Best cross-check 2026-06-25: PPA 96.1% / HO 97.1% corroboration, 105/105 interim-impact agreement (0 disagreements). 4 AM Best-only rows all 0% (coverage/recency, not value errors) -> both validated.
  { code: "OK", name: "Oklahoma",       data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-11 (interim->real): 235-row SERFF scrape, 415/415 cached, 0 misses (23-state streak). Cross-check (21st point): PPA 95.4% / HO 95.3%, value-agreement 101/101 (100%, 6th perfect) AFTER the B18 recovery — NEW_PRODUCT_RE matched DOI objection correspondence quoting another filing -> Safeco LBPM-134534930 +8.000%/7,566ph LIVE Prospect falsely dropped, adjudicated at source + surgically appended. SF eff-04/15/26 pair = SERFF-invisible watch items -> both validated
  { code: "OR", name: "Oregon",         data_coverage: true,  validated: { auto: true,  home: false } },
  { code: "PA", name: "Pennsylvania",   data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-15 (interim->real): 247-row SERFF scrape, 495/495 cached, 0 download misses (27-state streak). Cross-check (25th point): value-agreement 102/102 (100%), 0 material flags. Farmers Alliance (McPherson) tripwire state — 0 independents leaked; Farmers' & Mechanics' Mutual apostrophe-variant caught at the import brand gate and tripwired. +35 B19 window recoveries folded in pre-import (USAA PPA trio +7.3/+6.3/+5.9 on 106k combined; Liberty Mutual +7.1/+6.0 on 67k) -> both validated
  { code: "RI", name: "Rhode Island",   data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-07 (interim->real): 100-row SERFF scrape, 193/193 in-target cached, 0 true misses (11-state streak). AM Best cross-check (11th interim->real point): PPA 39/42 (92.9%; 3 AM-Best-only = 2 recency eff 04/20/26 + 1 adjudicated stale-stage) / HO 24/25 (96.0% — ROBUST N, coastal) -> adjudicated in-window 100%/100%; value-agreement 41/42 (the 1 differ = AM Best's OWN entity transposition on TRVD-G134527101, ours matches the source PDF); interim 40/41 (same transposition) -> effectively 0 disagreements. Coverage verdict: RICHNESS-ONLY x4 (incl. Encompass 8 SERFF = 6 form/rule + 2 new-product vs AM Best 0 — correct). TravCo Quantum Home captured via the search-term fix found at recon -> both validated
  { code: "SC", name: "South Carolina", data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-10 (interim->real): 196-row SERFF scrape, 354/354 cached, 0 misses (20-state streak). Cross-check (18th point): PPA 92.5% / HO 92.9%, value-agreement 56/58 (96.6%), 0 recoverable soft-misses; ENRICHMENT x2 AM Best lacks (GEICO -2.3%/9,390ph LIVE Defend + Encompass +4.6%/2,006) -> both validated
  { code: "SD", name: "South Dakota",   data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-08 (interim->real): 121-row SERFF scrape, 250/250 in-target cached, 0 download misses (13-state streak). AM Best cross-check (13th interim->real point): PPA 41/46 (89.1%) / HO 27/31 (87.1% — ROBUST N, hail country); adjudicated in-window 100%/100% (AM-Best-only = 8 recency + 1 rate-neutral amendment we drop by design); value-agreement 66/67 -> 67/67 adjudicated (the differ = AM Best carrying BOTH stages of a Safeco filing — original -6.0% + 0.0% amendment; our -6.0% matches the source PDF exactly); interim 58/59 -> 59/59. THE AK-TEST STATE: SD is COUNTRY's plains footprint and COUNTRY's entire SERFF presence = 1 Farmowners Form filing -> AM Best's 0 CORRECT; the Country-undercount does NOT reproduce (AK = lone thin case). Coverage RICHNESS-ONLY (Farmers 5/5 + Encompass 3/3 materials all in AM Best). 2 cached-but-0-rows parse anomalies adjudicated at the PDFs (both 0.000% rate-neutral; shape-L backlogged) -> both validated
  { code: "TN", name: "Tennessee",      data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-22 (interim->real, 42nd state — CHAIN COMPLETE): 322-row SERFF scrape, 413/413 targets cached in 17 bursts. Cross-check: value-agreement 139/141 (98.6%) with BOTH disagreements resolved OURS-CORRECT from PDFs (PRGS-134417055 Progressive Hawaii -3.0% verbatim in filed table, AM Best -0.1% is theirs; GMMX-134651170 Encompass Personal Umbrella +110.9%/1,490ph is REAL — AM Best's 6.3% was a matching collision with sibling GMMX-134648625, same entity+eff). PPA 102/112 (91.1%) / HO 69/71 (97.2%); all 12 AM-Best-only rows recency/immaterial — 0 material soft-misses. NEW PARSER CLASS fixed at this import: TN DOI embeds the state actuary's review memo whose per-coverage tables emitted 19 debris company rows across 3 filings (ALSE-134149698/FARM-134172973/NWPP-134180330; real rows unaffected; all 41 prior states scanned clean) — guard added in src/utils.py, TN rebuilt 341->322. Known class: CFPC-134388641 is a resubmission twin of CFPC-134282222 (identical company tables; AM Best keyed the resubmission's zeroed header) — kept per no-resubmission-dedup precedent. Mountain Laurel Assurance (Progressive TN vehicle) added to derive_brand, TN-first. Max active impact anchor moved to GMMX-134651170 +110.9% -> both validated
  { code: "TX", name: "Texas",          data_coverage: true,  source: "ambest" }, // PERMANENT (TDI, non-SERFF) — see AMBEST_PERMANENT_STATES
  { code: "UT", name: "Utah",           data_coverage: true,  validated: { auto: true,  home: false } },
  { code: "VT", name: "Vermont",        data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-06-30 (interim->real): 103-row SERFF scrape, 154/154 in-target. AM Best cross-check: PPA 26/32 (material in-window 42/42 = 100%) / HO 16/17 (94.1%, the 1 non-corrob immaterial) corroboration, interim 37/37 (100%) impact agreement — cleanest yet (0 disagreements, 0 soft-misses, 0 recoveries). Gap-class closure payoff: General Insurance Co of America captured proactively -> both validated.
  { code: "VA", name: "Virginia",       data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-06-22 (interim->real); AM Best cross-check: PPA 92.3%, HO values agree where they overlap (the 68.6% is AM Best-only coverage/recency, and the lone "disagreement" was AM Best's transposition the scrape got right) -> both validated
  { code: "WA", name: "Washington",     data_coverage: true,  validated: { auto: true,  home: false } },
  { code: "WV", name: "West Virginia",  data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-06-26 (interim->real): 113-row SERFF scrape, 207/207 filings. AM Best cross-check: PPA 30/33 (90.9%) / HO 9/10 (90%, lone miss pure recency -> 9/9 in-window) corroboration, 37/40 interim-impact agreement (the 3 diffs all AM-Best-side per source PDFs). Recovered the material Liberty Insurance Corporation HO (eff 01/09/25 -5%/7894ph) via a search-term fix -> both validated.
  { code: "WI", name: "Wisconsin",      data_coverage: true,  validated: { auto: true,  home: true  } }, // scraped 2026-07-13 (interim->real): 235-row SERFF scrape, 434/434 cached, 0 misses (26-state streak). Cross-check (24th point): value-agreement 109/109 (100%, 7th perfect); 3 flags all signal-neutral ±0.2% (B18-candidates folded into re-eval); blank max/min x38 = FIG source-blank family -> both validated
  { code: "WY", name: "Wyoming",        data_coverage: false }, // listed but no filings yet
];

export const COVERED_STATE_RECORDS: readonly StateRecord[] = STATES.filter(s => s.data_coverage);
export const COVERED_STATE_CODE_SET: ReadonlySet<string> = new Set(
  COVERED_STATE_RECORDS.map(s => s.code),
);

export function isCoveredState(code: string): boolean {
  return COVERED_STATE_CODE_SET.has(code);
}
